name: Build and Deploy Hexo Blog

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: yexca/vrchat-blog-web
          publish_branch: main 
          publish_dir: ./public 
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
